services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        VITE_API_URL: ${VITE_API_URL}
        VITE_SOURCE_URL: ${VITE_SOURCE_URL}
        VITE_GITHUB_URL: ${VITE_GITHUB_URL}
        VITE_TELEGRAM_URL: ${VITE_TELEGRAM_URL}
        VITE_LICENSE_URL: ${VITE_LICENSE_URL}
    ports:
      - "8080:8080"
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - blog
