services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.server
      args:
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
    env_file:
      - .env
    ports:
      - "8080:8080"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.client
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_SOURCE_URL: ${VITE_SOURCE_URL}
        VITE_GITHUB_URL: ${VITE_GITHUB_URL}
        VITE_TELEGRAM_URL: ${VITE_TELEGRAM_URL}
        VITE_LICENSE_URL: ${VITE_LICENSE_URL}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - server
