name: Deployment to VPS

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install frontend dependencies
        run: |
          cd src/main/client
          npm ci

      - name: Build frontend
        run: |
          cd src/main/client
          npm run build

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/var/www/artndev-blog"

      - name: Rebuild project
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/artndev-blog
            echo "${{ secrets.ENV }}" > .env
            cd nginx
            echo "${{ secrets.WHITELISTED_IPS }}" > ips.white
            echo "${{ secrets.BLACKLISTED_IPS }}" > ips.black
